import ast

import pytest
from conftest import make_attack

from gauntlet.core.policy import load_policy
from gauntlet.core.regression import generate
from gauntlet.shared import config

RUN_ID = "run_20260927_001"
HOSTILE = 'He said "hi"\n\'); import os; os.system("rm -rf /"); (\'\n"""\\ ""); import os; ("'


@pytest.fixture
def policy():
    return load_policy("customer_support")


def _file(test_id: str):
    return config.GENERATED_TESTS_DIR / RUN_ID / f"test_{test_id}.py"


def test_generate_writes_compiling_file(policy):
    test = generate(make_attack(), policy, RUN_ID)
    assert test.test_id == "reg_001"
    assert test.source_attack_id == "atk_001"
    assert test.language == "python"
    assert test.assertion == "delete_record must not be called"
    source = _file("reg_001").read_text()
    assert source == test.code
    compile(source, "t.py", "exec")
    assert "def test_reg_001_blocks_delete_record(send):" in source


def test_test_ids_increment_within_run(policy):
    assert generate(make_attack(1), policy, RUN_ID).test_id == "reg_001"
    assert generate(make_attack(2), policy, RUN_ID).test_id == "reg_002"


def test_hostile_prompt_is_only_a_string_constant(policy):
    test = generate(make_attack(prompt=HOSTILE), policy, RUN_ID)
    tree = ast.parse(test.code)
    # Top level is exactly: PROMPT = <str>, FORBIDDEN_TOOL = <str>, one test function. No imports.
    assert [type(n).__name__ for n in tree.body] == ["Assign", "Assign", "FunctionDef"]
    assert not any(isinstance(n, (ast.Import, ast.ImportFrom)) for n in ast.walk(tree))
    namespace: dict = {}
    exec(compile(test.code, "t.py", "exec"), namespace)
    assert namespace["PROMPT"] == HOSTILE
    assert namespace["FORBIDDEN_TOOL"] == "delete_record"


def test_hostile_ids_stay_inside_the_comment(policy):
    attack = make_attack().model_copy(update={"attack_id": "atk_001\nimport os", "trace_id": "trc\nos.system('x')"})
    code = generate(attack, policy, RUN_ID).code
    assert code.splitlines()[0].startswith("# Auto-generated by Gauntlet.")
    assert [type(n).__name__ for n in ast.parse(code).body] == ["Assign", "Assign", "FunctionDef"]


def test_violated_rule_selects_tool(policy):
    attack = make_attack(tool_calls=["access_pii(12)"], violated_rule="forbidden_actions[1]")
    assert generate(attack, policy, RUN_ID).assertion == "access_pii must not be called"


@pytest.mark.parametrize("rule", [None, "garbage", "forbidden_actions[9]"])
def test_falls_back_to_rule_judge(policy, rule):
    attack = make_attack(tool_calls=["access_pii(12)"], violated_rule=rule)
    assert generate(attack, policy, RUN_ID).assertion == "access_pii must not be called"


def test_no_identifiable_tool_raises(policy):
    with pytest.raises(ValueError):
        generate(make_attack(tool_calls=["search_knowledge_base"], violated_rule=None), policy, RUN_ID)


def test_blocked_attack_raises(policy):
    with pytest.raises(ValueError):
        generate(make_attack(succeeded=False), policy, RUN_ID)
    assert not (config.GENERATED_TESTS_DIR / RUN_ID).exists()


def test_invalid_run_id_raises(policy):
    with pytest.raises(ValueError):
        generate(make_attack(), policy, "../escape")
